name: Deploy
on: [deployement]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    strategy:
      matrix:
        deno-version: [1.33.1]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Build project
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ytd"
          entrypoint: "./server.ts" # TODO: update entrypoint

